export interface IUser {
  id: string | number,
  firstName?: string,
  lastName?: string,
  username?: string,
  gender?: string,
  age?: number,
  email?: string,
  phone?: string,
  address?: any,
  avatar: string,
  image: string,
  role?: string | number,
  bank?: any,
  birthDate?: string | null,
  userAgent?: string,
  university?: string,
  ip?: string,
};

export interface IProduct {
  id: string | number,
  title?: string,
  brand?: string,
  category?: string,
  sku?: string,
  stock?: number | string,
  price?: number,
  discountPercentage?: number,
  minimumOrderQuantity?: number,
  rating?: number,
  weight?: number,
  description?: string,
  thumbnail?: string,
  images?: any,
  dimensions?: any,
  tags?: any,
  meta?: any,
};

export interface IOrder {
  id: string | number,
  products?: Array<{
    id: string | number,
    title?: string,
    price?: number,
    quantity?: number,
    total?: number,
    discountPercentage?: number,
    discountedTotal?: number,
    thumbnail?: string,
  }> | any,
  total?: number,
  discountedTotal?: number,
  userId?: number,
  totalProducts?: number,
  totalQuantity?: number,
};
